name: Test, Build and Check PyPI Package
on: [push, pull_request]

jobs:
  test_build_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint
        run: |
          black --check . -l 120
          isort --profile black --check .

      - name: Test
        run: |
          python -m pytest

      - name: Build
        run: python setup.py sdist bdist_wheel

      - name: Check
        run: twine check dist/*

